def count(text=''):
    word_count = dict()
    for word in text.split():
        if word in word_count:
            word_count[word] += 1
        else:
            word_count[word] = 1
    return word_count

if __name__ == '__main__':
    str = "about me  i would love to think that i was some some kind of intellectual either the dumbest smart guy or the smartest dumb guy cant say i can tell the difference i love to talk about ideas and concepts i forge odd metaphors instead of reciting cliches like the simularities between a friend of mines house and an underwater salt mine my favorite word is salt by the way weird choice i know to me most things in life are better as metaphors i seek to make myself a little better everyday in some productively lazy way got tired of tying my shoes considered hiring a five year old but would probably have to tie both of our shoes decided to only wear leather shoes dress shoes  about you  you love to have really serious really deep conversations about really silly stuff you have to be willing to snap me out of a light hearted rant with a kiss you dont have to be funny but you have to be able to make me laugh you should be able to bend spoons with your mind and telepathically make me smile while i am still at work you should love life and be cool with just letting the wind blow extra points for reading all this and guessing my favorite video game no hints given yet and lastly you have a good attention spancurrently working as an international agent for a freight forwarding company import export domestic you know the works online classes and trying to better myself in my free time perhaps a hours worth of a good book or a video game on a lazy sundaymaking people laugh ranting about a good salting finding simplicity in complexity and complexity in simplicitythe way i look i am a six foot half asian half caucasian mutt it makes it tough not to notice me and for me to blend inbooks absurdistan the republic of mice and men only book that made me want to cry catcher in the rye the prince  movies gladiator operation valkyrie the producers down periscope  shows the borgia arrested development game of thrones monty python  music aesop rock hail mary mallon george thorogood and the delaware destroyers felt  food im down for anythingfood water cell phone shelterduality and humorous thingstrying to find someone to hang out with i am down for anything except a clubi am new to california and looking for someone to wisper my secrets toyou want to be swept off your feet you are tired of the norm you want to catch a coffee or a bite or if you want to talk philosophy"
    print(count(str))